2-UI/HaberWeb.UI/Controllers/UI/HomePageController.cs
using EntityLayer.Concrete;
using HaberWeb.UI.Dtos.CategoryDtos;
using HaberWeb.UI.Dtos.NewsDtos;
using HaberWeb.UI.Dtos.NewsImageDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using X.PagedList;

namespace HaberWeb.UI.Controllers.UI
{
    public class HomePageController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public HomePageController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }


        [Route("Haberler")]
        [AllowAnonymous]
        public async Task<IActionResult> Index(int categoryID)
        {

            var client = _httpClientFactory.CreateClient();
            var responserMessage = await client.GetAsync("https://api.vatan19tv.com/api/Category/news" + categoryID);
            var responserMessage2 = await client.GetAsync($"https://api.vatan19tv.com" +
                $"/api/NewsImage");
            var responserMessage3 = await client.GetAsync($"https://api.vatan19tv.com/api/Category");
            if (responserMessage.IsSuccessStatusCode)
            {
                var jsonData = await responserMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultNewsWithCategoryDto>>(jsonData);
                var imageJsonData = await responserMessage2.Content.ReadAsStringAsync();
                var imageValues = JsonConvert.DeserializeObject<List<ResultNewsImageDto>>(imageJsonData);
				var categoryJsonData = await responserMessage3.Content.ReadAsStringAsync();
				var categoryValues = JsonConvert.DeserializeObject<List<ResultCategoryDto>>(categoryJsonData);
				foreach (var news in values)
                {
                    news.NewsImage = imageValues
                        .Where(img => img.NewsID == news.NewsID)
                        .ToList();
                    news.Categories = categoryValues.Where(cat => cat.CategoryID == news.CategoryID).ToList();
                }
                return View(values);

            }
            return View();
        }

    }
}

2-UI/HaberWeb.UI/Controllers/UI/NewsDetailsController.cs
using EntityLayer.Concrete;
using HaberWeb.UI.Dtos.CategoryDtos;
using HaberWeb.UI.Dtos.NewsDtos;
using HaberWeb.UI.Dtos.NewsImageDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

namespace HaberWeb.UI.Controllers.UI
{
    public class NewsDetailsController : Controller
    {

        private readonly IHttpClientFactory _httpClientFactory;

        public NewsDetailsController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [Route("HaberDetayi")]
        [AllowAnonymous]
        public async Task<IActionResult> SingleContent(int newsID)
        {

            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://api.vatan19tv.com/api/News/{newsID}");
            var responserMessage2 = await client.GetAsync($"https://api.vatan19tv.com/api/NewsImage");
            var responserMessage3 = await client.GetAsync($"https://api.vatan19tv.com/api/Category");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<ResultNewsDto>(jsonData);
                var imageJsonData = await responserMessage2.Content.ReadAsStringAsync();
                var imageValues = JsonConvert.DeserializeObject<List<ResultNewsImageDto>>(imageJsonData);
                var categoryJsonData = await responserMessage3.Content.ReadAsStringAsync();
                var categoryValues = JsonConvert.DeserializeObject<List<ResultCategoryDto>>(categoryJsonData);

                values.NewsImage = imageValues
                .Where(img => img.NewsID == values.NewsID)
                .ToList();
 
                return View(new List<ResultNewsDto> { values });

            }
            return View();
        }
    }
}

2-UI/HaberWeb.UI/Views/NewsDetails/SingleContent.cshtml
@model List<ResultNewsDto>

@{


 
    {
        @foreach (var item in Model)
        {
            ViewData["Title"] = item.NewsTitle;
            ViewData["Description"] = item.NewsSummary;


            foreach (var image in item.NewsImage)
            {
 
                ViewData["ogImage"] = image.Path;
            }

        }



        Layout = "~/Views/Default/Index.cshtml";
    }
}

<section class="block-wrapper no-sidebar">
    <div class="container">

        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="single-post">
                    @foreach (var item in Model)
                    {
                        <div class="post-header mb-5 text-center">

                            <a class="post-category " href="@Url.Action("Index", "HomePage", new { categoryID = item.CategoryID })">İlgili Kategoriye Git</a>
                            <p style="font-size:13px">@item.NewsEnterTime</p>
                            <h1 class="post-title" data-newstitle="@item.NewsTitle">
                                @item.NewsTitle
                            </h1>
                            <p>

                                @item.NewsSummary
                            </p>
                        </div>
                        <div class="post-body">
                            <div class="post-featured-image">
                                @foreach (var image in item.NewsImage.Where(x => x.ContentImage == false))
                                {
                                    <img height="500px" width="750px" src="https://api.vatan19tv.com/@image.Path" class="" alt="featured-image" data-newsimage="https://api.vatan19tv.com/@image.Path">

                                }

                                <div class="social-media-links text-center" style="margin-right: 10px;font-size:5px;">
                                    <div class="fb-share-button" style="display: inline-block;"
                                         data-href="https://www.vatan19tv.com/HaberDetayi?newsID=@item.NewsID"
                                         data-layout=""
                                         data-size=""
                                    >
                                        <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.vatan19tv.com%2FHaberDetayi%3FnewsID%3D@item.NewsID&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"></a>
                                    </div>
                                    <div style="display: inline-block;margin-right: 30px;margin-left:30px;font-size:40px;">
                                        <a class="fa fa-twitter"
                                           style="font-size:30px"
                                           href="https://twitter.com/share?url=https://www.vatan19tv.com/HaberDetayi?newsID=@item.NewsID&amp;text=@item.NewsTitle...Haber Detayları için tıklayınız..."
                                           data-size=""
                                           target="_blank">
                                        </a>
                                    </div>
                                    <div style="display: inline-block;">
                                        <a class="fa fa-whatsapp"
                                           style="font-size:30px; color:green;"
                                           href="https://api.whatsapp.com/send?text=@item.NewsTitle%20-%20Haber%20Detayları%20için%20tıklayınız:%20https://www.vatan19tv.com/HaberDetayi?newsID=@item.NewsID"
                                           target="_blank">
                                        </a>
                                    </div>
                                </div>


                            </div>


                            <div class="entry-content">
                                <p>
                                    @item.NewsContent
                                </p>
                                @foreach (var image in item.NewsImage.Where(x => x.ContentImage == true))
                                {
                                    <div class="text-center">
                                        <img height="400px" width="550px" src="https://api.vatan19tv.com/@image.Path" class="" alt="featured-image" style="margin-bottom:30px;margin-top:30px">
                                    </div>
                                }
                                <div class="media mb-4 single-media">

                                    <div class="media-body">
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

<script async defer crossorigin="anonymous" src="https://connect.facebook.net/tr_TR/sdk.js#xfbml=1&version=v18.0" nonce="XkAwVPZK"></script>
<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<!-- Your share button code -->