2-UI/HaberWeb.UI/Controllers/UI/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HaberWeb.UI.Controllers.UI
{
	public class DefaultController : Controller
	{
        [AllowAnonymous]
        public IActionResult Index()
		{
			return View();
		}
	}
}

2-UI/HaberWeb.UI/Controllers/UI/UIHomePageController.cs
using HaberWeb.UI.Dtos.NewsDtos;
using HaberWeb.UI.Dtos.NewsImageDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

namespace HaberWeb.UI.Controllers.UI
{
	public class UIHomePageController : Controller
	{
        private readonly IHttpClientFactory _httpClientFactory;

        public UIHomePageController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [Route("")]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {

            var client = _httpClientFactory.CreateClient();
            var responserMessage = await client.GetAsync("https://api.vatan19tv.com/api/News/ListNewsWithCategory");
            var responserMessage2 = await client.GetAsync($"https://api.vatan19tv.com/api/NewsImage");
            if (responserMessage.IsSuccessStatusCode)
            {
                var jsonData = await responserMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultNewsWithCategoryDto>>(jsonData);
                var imageJsonData = await responserMessage2.Content.ReadAsStringAsync();
                var imageValues = JsonConvert.DeserializeObject<List<ResultNewsImageDto>>(imageJsonData);
                foreach (var news in values)
                {
                    news.NewsImage = imageValues
                        .Where(img => img.NewsID == news.NewsID)
                        .ToList();
                }
                return View(values);

            }
            return View();
        }
    }
}

2-UI/HaberWeb.UI/Views/Shared/Components/_UINavbarPartial/Default.cshtml
@model List<ResultCategoryDto>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="main-navbar clearfix bg-dark ">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg site-main-nav navigation">
                    <a class="navbar-brand d-lg-none" href="@Url.Action("Index","UIHomePage")">
                        <img src="~/newsbit-bootstrap-main/theme/images/logos/kanal-logo.png" alt="" width="143px" height="43px">
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:red">
                        <span class="fa fa-bars"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">

                            <li class="nav-item dropdown">
                                <a class="nav-link" href="@Url.Action("Index","UIHomePage")" role="button">
                                    Anasayfa
                                </a>
                                @foreach (var item in Model)
                                {
                                    <a class="nav-link" href="@Url.RouteUrl("Haberler", new { categoryId = item.CategoryID })" role="button">
                                        @item.CategoryName
                                    </a>

                                }

                            </li>

                        </ul>
                    </div>
                </nav>
              
            </div>
        </div>
    </div>

</div>
 